# Generated by Django 5.0 on 2023-12-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordData', '0003_alter_word_example_alter_word_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
