# Generated by Django 5.0 on 2023-12-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_words_audio_words_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='audio',
        ),
        migrations.AlterField(
            model_name='words',
            name='definition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
