# Generated by Django 5.0 on 2023-12-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_remove_words_definition_words_definitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='definitions',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='words',
            old_name='text',
            new_name='word',
        ),
    ]
